import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#1a1a2e' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#16213e',
  },
  headerTitle: { color: '#fff', fontSize: 16, fontWeight: '700' },
  cancelBtn: { minWidth: 60 },
  cancelText: { color: '#aaa', fontSize: 14 },
  resetBtn: { minWidth: 60, alignItems: 'flex-end' },
  resetText: { color: '#e74c3c', fontSize: 14 },
  scroll: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 8 },
  sectionTitle: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginTop: 20,
    marginBottom: 10,
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  groupLabel: {
    color: '#555',
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginTop: 12,
    marginBottom: 8,
  },
  yearInput: {
    backgroundColor: '#16213e',
    color: '#fff',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    width: 120,
    borderWidth: 1,
    borderColor: '#0f3460',
  },
  footer: { padding: 16, borderTopWidth: 1, borderTopColor: '#16213e' },
  applyBtn: { backgroundColor: '#e74c3c', borderRadius: 10, paddingVertical: 14, alignItems: 'center' },
  applyBtnText: { color: '#fff', fontSize: 15, fontWeight: '700' },
});
