import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#1a1a2e' },
  scroll: { flex: 1 },
  scrollContent: { alignItems: 'center', padding: 24, paddingBottom: 40 },
  closeBtn: { position: 'absolute', top: 48, right: 20, zIndex: 10, padding: 8 },
  closeBtnText: { color: '#aaa', fontSize: 22, lineHeight: 24 },
  badge: {
    backgroundColor: '#e74c3c',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 6,
    marginTop: 64,
    marginBottom: 16,
  },
  badgeText: { color: '#fff', fontSize: 12, fontWeight: '700', letterSpacing: 1.2 },
  title: { color: '#fff', fontSize: 28, fontWeight: '800', textAlign: 'center', marginBottom: 10 },
  subtitle: { color: '#888', fontSize: 15, textAlign: 'center', lineHeight: 22, marginBottom: 32 },
  benefitsList: { width: '100%', gap: 14, marginBottom: 36 },
  benefit: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  benefitIcon: { fontSize: 22, width: 32, textAlign: 'center' },
  benefitText: { color: '#ddd', fontSize: 15 },
  packagesRow: { width: '100%', gap: 12, marginBottom: 28 },
  package: {
    borderWidth: 1.5,
    borderColor: '#16213e',
    borderRadius: 12,
    padding: 16,
    backgroundColor: '#16213e',
  },
  packageSelected: { borderColor: '#e74c3c', backgroundColor: '#1e0f0f' },
  packageTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  packageTitle: { color: '#fff', fontSize: 16, fontWeight: '700' },
  packageBadge: {
    backgroundColor: '#e74c3c',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  packageBadgeText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  packagePrice: { color: '#aaa', fontSize: 13, marginTop: 4 },
  purchaseBtn: {
    width: '100%',
    backgroundColor: '#e74c3c',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 14,
  },
  purchaseBtnDisabled: { backgroundColor: '#555' },
  purchaseBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  restoreBtn: { paddingVertical: 8 },
  restoreBtnText: { color: '#888', fontSize: 13 },
  legalText: { color: '#555', fontSize: 11, textAlign: 'center', marginTop: 16, lineHeight: 16 },
  loadingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center' },
});
