import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#1a1a2e' },
  section: { padding: 16 },
  sectionTitle: { color: '#fff', fontSize: 16, fontWeight: '700', marginBottom: 16 },
  option: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 8,
    backgroundColor: '#16213e',
    marginBottom: 10,
    gap: 12,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  optionSelected: { borderColor: '#e74c3c' },
  radio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#555',
  },
  radioSelected: { borderColor: '#e74c3c', backgroundColor: '#e74c3c' },
  optionText: { flex: 1 },
  optionLabel: { color: '#ccc', fontSize: 14, fontWeight: '600', marginBottom: 2 },
  optionLabelSelected: { color: '#fff' },
  optionDesc: { color: '#666', fontSize: 12 },
  premiumBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1e0f0f',
    borderWidth: 1.5,
    borderColor: '#e74c3c',
    borderRadius: 10,
    padding: 16,
  },
  premiumBannerTitle: { color: '#fff', fontSize: 15, fontWeight: '700', marginBottom: 2 },
  premiumBannerSubtitle: { color: '#aaa', fontSize: 12 },
  premiumBannerArrow: { color: '#e74c3c', fontSize: 24 },
});
